### ISSUE TITLE
Won't work with Sass 3.3.0 (just released)

### ISSUE THREAD

**Issue by corysimmons** [mojotech/sass2stylus#3]
Between Sass 3.2.15 and 3.3.0 `node_name` in the `ToStylus` method breaks returning this error:

`converter.rb:9:in`visit': undefined method `node_name' for #<ToStylus:0x007ffe910b4978> (NoMethodError)`
